### ISSUE TITLE
Exported maps from Bridge does not convert to proper Octane nodes

### ISSUE THREAD

**Issue by binkarr** [Yichen-Dou/OC-Blender-Helper-Addon#11]
Hi, 
when I export a map from Bridge, it exports without any problems but in Octane Blender, when i look at the material in the node editor all I see is a Universal Material node, and no maps. It seems it is not correctly converting the node structure? 

Im using the latest Blender Octane Free tier, 2020.2._23.1 

Any idea?

**Comment by Yichen-Dou** [comment]
Hi.  Could u take a screenshot of the Blender console for me? That's at Topbar>Window>Toggle system console.  Let me know what's the error message when you import the asset.  ty

**Comment by binkarr** [comment]
I have attached a screenshot! I have no issues importing assets when the cycles render is selected. But when I have octane selected all i get is a lonely universal material node in the material. Same when importing a mesh, the actual mesh geo imports well but the material is just a universal material node. 
<img width="1020" alt="blender_eagkpWPIZg" src="https://user-images.githubusercontent.com/78915875/107655380-d1204280-6c83-11eb-91bf-b971bc37a60e.png">

**Comment by binkarr** [comment]
oh i just read the console, and i tried removing the MSPlug blabla folder in the userprefs, and it works now, sorry i should have read the console myself first :)

**Comment by Yichen-Dou** [comment]
No problem. I'm glad to help. The new Octane blender tool - Octaner is on the way, which is an individual app that includes a library function containing users assets and downloaded megascans as well. At that time, issues caused by having the official add-on no longer exists. Please take a look on this git after a period of time ty

**Comment by binkarr** [comment]
Cool, will definitely check back. There are still some annoying things not sorted out in the Octane plugin, that i think Otoy has to fix :( Like for an example, live boolean objects still render in the preview render. (in cycles the cutters are invisible in the preview render, while only showing the "cut", but still visible in the other viewports so you can edit it). Doesnt seem to be anyway to fix this in Octane. I can disable/hide it in viewport in the outliner, but this also hides it completely so i cant edit the boolean cutter.

**Comment by Yichen-Dou** [comment]
I'm not in front of my computer to test it,  but the best choice for you would be toggling on/off object visibility on camera (render mode). This can be done under Octane Helper > Render > Change object properties. I guess there is a setting called "Visible on camera"? After you unchecked that option, click "copy settings to all selected objects"

**Comment by binkarr** [comment]
yeah i tried that.. it makes the boolean cut black. like attached image.
but it should be just a cut, like the 2nd image.
anyways.. i think this is something the octane plugin devs has to fix.
There was a similar issue in Luxcore a long time ago, that they fixed.

**Comment by Yichen-Dou** [comment]
Actually it shouldn't be like that.. Not sure what's going on. If you are interested, please join the Octane Blender Plugin Facebook group

**Comment by binkarr** [comment]
Thanks, I'll check it out.

**Comment by binkarr** [comment]
There was a solution proposed, and its this one (hope you can see this
link):
https://www.facebook.com/photo.php?fbid=3907615015952938&set=p.3907615015952938&type=3
By changing the octane offset transform enabled scale to 0.
However doing this for every cutter object is a pain in the ass..
If Octane does not want to fix this in their addon, do you think you could
add it as a shortcut to the Quick menu (W)?
