### ISSUE TITLE
No textures when imported megascans assets

### ISSUE THREAD

**Issue by Turing-Zhao** [Yichen-Dou/OC-Blender-Helper-Addon#13]
When using megascans to import assets, there will be a new material but with no textures, have to import textures manually. The textures export settings are albedo, specular, roughness, normal and displacement.

**Comment by Yichen-Dou** [comment]
Hi.  could you please take a screenshot of the Blender Console when a error occurres

**Comment by Turing-Zhao** [comment]
<img width="1648" alt="截屏2021-03-16 下午1 54 50" src="https://user-images.githubusercontent.com/80594431/111262444-40140100-865f-11eb-8b04-ed195a6b2107.png">
As you can see, after exporting the megascans asset to blender, there is an object but with no textures, and I can find a new material in the material slot, but it is just a universal material. My exporting settings are albedo, specular, roughness, normal and displacement.

**Comment by Yichen-Dou** [comment]
Please take a screenshot of the Blender console. I guess it's probably because you have the official quixel add-on in your user folder that's why the octane megascans module is not used and failed to import.  see QA in the repository

**Comment by Turing-Zhao** [comment]
<img width="1648" alt="截屏2021-03-16 下午6 47 52" src="https://user-images.githubusercontent.com/80594431/111297115-3bb00e00-8688-11eb-8c05-91228293bc89.png">
Here it is the blender console, no error warning in the exporting process, but no textures in the node tree.

**Comment by Yichen-Dou** [comment]
no this is not the blender console. please go topbar Window > Toggle system console.  I'm pretty sure you have the official quixel add-on installed,  because by default my module will import materials with a prefix in name - "MS_"

**Comment by Turing-Zhao** [comment]
You are right, I'v solved this problem. Even though removed that official add-on in Blender, I have to delete that add-on folder manually. It's unhappy that MacOS hide something in it's finder, so I need to press the command+shift+G to go to /Users/Username/Library/Application Support/Blender/2.XX/scripts/startup, the official add-on is in the startup folder, delete the startup folder and restart blender, it works. Thanks.
