### ISSUE TITLE
Import image as planes?

### ISSUE THREAD

**Issue by aeon3** [Yichen-Dou/OC-Blender-Helper-Addon#14]
Hey hello,

I was wondering how do you feel about integrating the "import image as planes" addon that works with cycles/eevee into octane helper. That would be a huge time saver :)

cheers!

**Comment by Yichen-Dou** [comment]
Hi, I'm not sure if you like this way
1. Create a plane
2. Right-Click Menu > Materials > Pattern Material
3. (Optional) Turn on modifier options when selecting an image file
![Img1](https://user-images.githubusercontent.com/58964972/112334463-66d4d600-8cf6-11eb-8e8b-24ecb4d26038.png)
![Img2](https://user-images.githubusercontent.com/58964972/112334863-b9ae8d80-8cf6-11eb-94d3-b6e55d6eec21.png)
This mostly works for the alpha image I believe, I may update some extra features to it in the next version

**Comment by Yichen-Dou** [comment]
and, when all modifiers are turned on, just select a target in the shrinkwrap modifier and move the plane to use it in this way
![s](https://user-images.githubusercontent.com/58964972/112335607-58d38500-8cf7-11eb-8425-b445aafd13fc.png)

**Comment by aeon3** [comment]
awesome, thank you!

**Comment by aeon3** [comment]
actually the problem with that method is that the plane doesnt get automatically resized based on the ratio of the picture. I was trying to add an image backdrop of mountains or trees. the big benefit from import image as plane is that all the ratio/uv/size is done for me :)
