### ISSUE TITLE
请求:我留意到这个只有英文版，我打算把它的中英翻译加入到MO文件中

### ISSUE THREAD

**Issue by cx1132692358** [Yichen-Dou/OC-Blender-Helper-Addon#2]
如题：
我留意到这个只有英文版，我打算把它的中英翻译加入到MO文件中，然后借助开源插件万物有灵，就能够直接秒切中英文了。
（额外，我最近打算制作开源的blender octane教程...请问如果我引用到这个插件，除了公布下载地址还有什么额外需要注意的么~这是我的B站链接：https://www.bilibili.com/https://space.bilibili.com/35723238）

**Comment by cx1132692358** [comment]
![image](https://user-images.githubusercontent.com/18584564/84126883-15ae6b00-aa71-11ea-887e-4ecdce19b216.png)

**Comment by Yichen-Dou** [comment]
哈哈。没什么特别的，录制视频提供个Git项目地址即可。你要是要二次开发，未来做商业用途售卖的话，唯一要注意的是Icons文件夹下的Octane Logo，虽然是我基于他们的logo制作的，但没得到授权时不得乱来（不得侮辱，用于其它项目，商用等）。你要是移除了logo倒是可以商用，根据GPL的规定就可以。录制视频和汉化项目没事

**Comment by cx1132692358** [comment]
我并没有想过商业售卖和二次开发....事实上我主要是想在做教程的时候用一下它，它真的太香了哈哈...
（这是我开发的一个插件（资产管理）最近它也支持OC了）1132692358求个好友位

**Comment by cx1132692358** [comment]
https://www.bilibili.com/video/BV1xp4y1X7ef

**Comment by Yichen-Dou** [comment]
👍干巴爹
