### ISSUE TITLE
megascan assets are imported without material output connected

### ISSUE THREAD

**Issue by aeon3** [Yichen-Dou/OC-Blender-Helper-Addon#4]
Hi!

I am using the latest helper 2.7.6 with octane blender 2.82 and I found this small bug. Imported assets come without the material output. Unfortunately I have issue with the latest 2.83.1 and that is why Im using an older version. Not sure if it's worth fixing if it works in 2.83 but jut putting it out there!

Thanks

**Comment by Yichen-Dou** [comment]
Hi. Could u please check the log in Blender console for me?

**Comment by aeon3** [comment]
Sure.

`OctaneBlender Engine Create
OctaneBlender Engine Free
FBX Import: start importing C:\Users\Allan\Documents\Megascans Library\Downloaded\3d\rock_cliffs_uchwaffda\uchwaffda_LOD0.fbx
FBX version: 7500
        FBX import: Prepare...
                Done (0.000000 sec)

        FBX import: Templates...
                Done (0.000000 sec)

        FBX import: Nodes...
                Done (0.000000 sec)

        FBX import: Connections...
                Done (0.000000 sec)

        FBX import: Meshes...
                Done (0.296875 sec)

        FBX import: Materials & Textures...
                Done (0.000000 sec)

        FBX import: Cameras & Lamps...
                Done (0.000000 sec)

        FBX import: Objects & Armatures...
                Done (0.000000 sec)

        FBX import: ShapeKeys...
                Done (0.000000 sec)

        FBX import: Animations...
                Done (0.000000 sec)

        FBX import: Assign materials...
                Done (0.000000 sec)

        FBX import: Assign textures...
                Done (0.000000 sec)

        FBX import: Cycles z-offset workaround...
                Done (0.000000 sec)

        Done (0.296875 sec)

Import finished.
Imported an asset from Quixel Bridge
OctaneBlender Engine Create
OctaneBlender Engine Free`

**Comment by Yichen-Dou** [comment]
Hmm. I tested the same asset "Quarry Cliff" and everything works fine here. Please give me some time to figure out why.

**Comment by aeon3** [comment]
Yes with the latest OC blender it imports correctly. The only reason Im not using it is because there's an issue with texture displacement in 2.83 which is not present in 2.82. Hopefully they will fix it soon!

**Comment by Yichen-Dou** [comment]
Unfortunately I can't find a possible reason. 

I use:
Latest OC Blender
Latest helper addon (no need to click anything like we did in my previous MS Livelink add-on)
Latest Bridge App 
Removed the official add-on Bridge automatically put into your Blender preferences folder
Please restart Blender if you have installed it before

If you scroll up can u see other error messages?

**Comment by Yichen-Dou** [comment]
I just saw your last message. Yeah I know that. That's why I set default displacement mode to vertex displacement now. Not sure about 2.82 because a lot of things changed and there were some new features which causes my add-on to crush in 2.83.
Please use add-ons between 2.6.1 to 2.7.3 for Blender 2.82 (inclusive)

**Comment by aeon3** [comment]
Got it thanks you!
